# WeatherbysApp

## Requirements
Poll SOAP XML API and store the data in a DB

There is some data that isn't available in the SOAP XML. So will need to build a CMS for manual user entry to collate the extra fields that are missing and store them into the DB to go along side the polling of the SOAP XML above. We will provide a list of fields/data we need to collect in the CMS shortly. The CMS will not need to do anything more in terms of front end (such as all the features the app will have - just needs to provide APIS to do it)


The apps when performing the API calls will get the data in JSON of the above two combined data.

## Hostage
The client will provide a hostage for the server with your requirements (windows/linux/etc).

## HTTPS / SSL
It needs to supports SSL. The client will provide a certificate with your requirements.

## JSON & JSONP Response Format
All API calls must be REST and support a single format: JSON. Add a callback parameter to your request and the response will be encapsulated in the value you specified.

## Allowed HTTPs requests

- `POST` - To create a resource
- `PUT` - To  update a resource
- `PATCH` - To  update a resource
- `GET` - Get a resource or list of resources
- `DELETE` - To delete resource

## Server Responses

- 200 `OK` - the request was successful (some API calls may return 201 instead).
- 201 `Created` - the request was successful and a resource was created.
- 204 `No Content` - the request was successful but there is no representation to return (i.e. the response is empty).
- 400 `Bad Request` - the request could not be understood or was missing required parameters.
- 401 `Unauthorized` - authentication failed or user doesn't have permissions for requested operation.
- 403 `Forbidden` - access denied.
- 404 `Not Found` - resource was not found.
- 405 `Method Not Allowed` - requested method is not supported for resource.
- 429 `Too Many Requests` - exceeded KirkeWeb API limits. Pause requests, wait up to one minute, and try again.

## Encoding

All endpoints accept and use UTF-8 encoding

## Dates

All dates will be in ISO-8601 format in UTC timezone: `yyyy-MM-dd'T'HH:mm:ss'Z'`

# Group Sponsor
#GET /sponsor

To return the URL of an image (or a base64 encoded image) of the sponsor to use in the apps. The apps will download the image to display in apps.

+ Response 200 (application/json)
    + Attributes
        + sponsorId: 147483647 (number, required) - ID of the sponsor in the form of an long
        + sponsorName: `SkyBet` (string, required)
        + createdAt: `2015-11-30T09:35:10.652Z` (string, required) - server created date
        + updatedAt: `2015-11-30T09:35:10.652Z` (string, required) - server updated date
        + imageUrl: `http://www.url.co.uk/image.jpg` (string, required)
        + success: true (boolean, required)
        
+ Response 403 (application/json)
    + Attributes (error)

# Data Structures

## error (object)
+ success: false (boolean, required)
+ error (object) - Error object
    + errorCode: 403 (number)
    + errorMessage: `Your session has expired, please sign-in and try again.` (string)
